### ISSUE TITLE
Couldn't write/connect to socket. 

### ISSUE THREAD

**Issue by RonnyDT** [medariox/Scrapeer#12]
Hi medariox, 

Since today i've not been able to get any seed/peer data because of socket issues on my live webhosting/domain. Localwebhost works fine. This issue probably lies at my hoster's end I suppose? Note: all the "couldn't write/connect to socket" trackers are UDP.

`Array ( [0] => Invalid scrape connection (explodie.org:6969). [1] => Invalid scrape response (tracker.tfile.me:80). [2] => Invalid scrape connection (bigfoot1942.sektori.org:6969). [3] => Couldn't write to socket. [4] => Couldn't write to socket. [5] => Couldn't write to socket. [6] => Couldn't write to socket. [7] => Couldn't connect to socket. [8] => Couldn't write to socket. [9] => Couldn't write to socket. [10] => Couldn't write to socket. [11] => Couldn't write to socket. [12] => Couldn't connect to socket. [13] => Couldn't write to socket.  )`

Any ideas?

**Comment by medariox** [comment]
Sounds like your provider is blocking outgoing UDP requests. Your best bet would be to ask them directly.

**Comment by RonnyDT** [comment]
Ok just what I thought. Thanks for confirming!
