### ISSUE TITLE
peers

### ISSUE THREAD

**Issue by ValenokPC** [medariox/Scrapeer#13]
Можно сделать выбор между announce и scrape

**Comment by medariox** [comment]
Can you try to explain in English? Google translate didn't help.

**Comment by teamcoltra** [comment]
I think what @ValenokPC is asking is for the option be able to choose between getting peers from either the announce by connecting to the torrent or by scrape which is an option provided by some (all?) trackers.

**Comment by medariox** [comment]
Thanks @teamcoltra, this makes sense.

I will try to implement it in the upcoming release.

**Comment by medariox** [comment]
This has been added to the current version. Check out [Announce scraping](https://github.com/medariox/Scrapeer#announce-scraping) on how to use it.
