### ISSUE TITLE
how to read scrape file ?

### ISSUE THREAD

**Issue by ghost** [medariox/Scrapeer#16]
there are some trackers which are providing scrape file, which has all the infohashes which are using the tracker and seeders and leechers count., 

e.g. 
http://coppersurfer.tk/
The full aggregated scrape file is updated every 1 hour. The name of full scrape file may change in the future.
here : http://coppersurfer.tk/full_scrape_not_a_tracker.tar.gz

after unzipping i get scrape file which is 396 MB.

how can i use your library to read the file ? or is there any other way ?

Thanks

**Comment by medariox** [comment]
I don't know how to read that file honestly, but Scrapeer is definitely not the right tool for it.

**Comment by ghost** [comment]
nvm., i found solution., thanks.
