### ISSUE TITLE
My Srape return information from 1 tracker inseatd of 30

### ISSUE THREAD

**Issue by Machou** [medariox/Scrapeer#19]
Hi

I use this code :

```php
require 'cfg/class.scraper.php';
$scraper = new Scrapeer\Scraper();

$trackers = array(_ARRAY_OF_30_TRACKERS_);
$hash = array( '03BB57EA1F7E8DC9CC7DA349B549D7A7C5BC3359' );

$info = $scraper->scrape( $hash, $trackers );
```

He return only 1 info :

> Array
> (
>     [03BB57EA1F7E8DC9CC7DA349B549D7A7C5BC3359] => Array
>         (
>             [seeders] => 293
>             [completed] => 19740
>             [leechers] => 38
>         )
> 
> )

Why doesn't it return the information from all the scrapped trackers?

**Comment by medariox** [comment]
This is how it is supposed to work, see: https://github.com/medariox/scrapeer#single-info-hash-and-multiple-trackers-recommended-usage

> First tracker in the array will be used, if it fails (invalid tracker, invalid info-hash or invalid info-hash for that tracker) the second tracker will be used and so on.

**Comment by Machou** [comment]
In fact, I thought that if I scrapped 30 trackers, he would give me the information from the 30 trackers, not the 1st functional one.

So I made a loop that checks each tracker 1 by 1 and returns the results in a array.

**Comment by medariox** [comment]
That's the correct way to do it. Scrapeer won't provide that functionality, because scraping every tracker for each torrent is something very inefficient to do, that should possibly be avoided.

**Comment by Machou** [comment]
ok thanks, so it's not a bug; i close :p
