### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Scrapeer\socket_create()

### ISSUE THREAD

**Issue by talk2rajasimman** [medariox/Scrapeer#21]
Hi, I am new in Torrent I am facing this issue. please reply me ASP.

Fatal error: Uncaught Error: Call to undefined function Scrapeer\socket_create() in C:\xampp\htdocs\scrapeer-master\scraper.php:426 Stack trace: #0 C:\xampp\htdocs\scrapeer-master\scraper.php(409): Scrapeer\Scraper->udp_create_connection('tracker.coppers...', 6969) #1 C:\xampp\htdocs\scrapeer-master\scraper.php(382): Scrapeer\Scraper->prepare_udp('tracker.coppers...', 6969) #2 C:\xampp\htdocs\scrapeer-master\scraper.php(174): Scrapeer\Scraper->scrape_udp(Array, 'tracker.coppers...', 6969, false) #3 C:\xampp\htdocs\scrapeer-master\scraper.php(101): Scrapeer\Scraper->try_scrape('udp', 'tracker.coppers...', 6969, '', false) #4 C:\xampp\htdocs\scrapeer-master\test.php(8): Scrapeer\Scraper->scrape(Array, Array) #5 {main} thrown in C:\xampp\htdocs\scrapeer-master\scraper.php on line 426

**Comment by Machou** [comment]
Several solutions are possible, since you are on XAMPP,

Either you activate your firewall
You activate the sockets
See with your network

**Comment by scriptzteam** [comment]
use linux :D
