### ISSUE TITLE
error

### ISSUE THREAD

**Issue by egbertosullivan** [medariox/Scrapeer#23]
I was unable to use the class, every time I execute it the error in the function udp_create_connection() line 426.
the line @socket_create.

I'm not able to solve it, I wonder if you could help me.

![error](https://user-images.githubusercontent.com/39571029/90242947-5a090f00-de04-11ea-8d06-b6f7232aa9f8.png)

**Comment by medariox** [comment]
`socket_create()` ist a PHP function available since version 4.1.0. You are probably using a very old and unsupported PHP version.

**Comment by egbertosullivan** [comment]
I'm using the php 7.2.32

**Comment by kktsvetkov** [comment]
Needs a backslash added to seek it in the global namespace, since now it looks for it in the project's namespace, e.g. `\socket_create()`

**Comment by egbertosullivan** [comment]
thanks, I will test here

**Comment by medariox** [comment]
Probably missing the socket extension then, see: https://stackoverflow.com/questions/6137823/fatal-error-call-to-undefined-function-socket-create

Anyway, closing since you didn't post your code and it's just a guessing game at this point.

**Comment by egbertosullivan** [comment]
very godd, now it worked

thanks
