### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KaRpIkS** [medariox/Scrapeer#5]
```
$tracker = array('http://bt01.nnm-club.cc:2710/0055b4edb53392b5ac41b79d29131591/announce');
$hash = array( '0e1b1a2f5be209e1157c148faaf8afd3a3aa3824' );

$info = $scraper->scrape( $hash, $tracker );

echo "<pre>";
print_r( $info );
echo "</pre>";
```

`Warning: file_get_contents(http://bt01.nnm-club.cc:2710/scrape?info_hash=%0E%1B%1A%2F%5B%E2%09%E1%15%7C%14%8F%AA%F8%AF%D3%A3%AA8%24): failed to open stream: HTTP request failed! in ...\scraper.php on line 243`

> К удалённым объектам обращаться только через сокеты или cURL'ом.

**Comment by medariox** [comment]
Thanks for the bug report.

I just pushed new version, could you please try it and report back? It's working fine on my end with the code example you provided.

I'm not sure what you want to do with cURL exactly, but I'd like to avoid an external dependency.
Make sure that ```allow_url_fopen``` is active in your PHP config file.

**Comment by KaRpIkS** [comment]
@medariox Thank you everything works. The error is no more!
